apiRules:
- exclude:
    uidRegex: ^System\.
    type: Namespace
- exclude:
    uidRegex: ^Microsoft\.
    type: Namespace
- exclude:
    hasAttribute:
      uid: System.ObsoleteAttribute
- include:
    uidRegex: ^ProjectName\.
    type: Namespace
